export const ESKIN_BOOTS_DATA = {
  business: {
    name: 'Eskin Boots',
    onboarding_status: 'ready' as const,
  },
  brand: {
    business_name: 'Eskin Boots',
    tagline: 'Artesania y calidad en cada paso',
    target_customers: 'Mujeres y hombres de 18 a 45 anos que buscan botas de piel genuina de calidad artesanal. Amantes del estilo western, moda casual y elegante. Clientes que valoran la calidad sobre el precio y buscan piezas unicas que cuenten su historia.',
    differentiators: 'Somos fabricantes artesanales de Leon, Guanajuato. Cada par de botas esta hecho a mano con piel genuina de la mas alta calidad. No somos revendedores, somos los creadores. Disenos exclusivos que combinan tradicion mexicana con tendencias actuales.',
    elevator_pitch: 'Eskin Boots es una marca mexicana de calzado de piel genuina, fabricado artesanalmente en Leon, Guanajuato. Creamos botas premium con materiales de la mas alta calidad y disenos unicos que combinan la tradicion western con la moda contemporanea. Cada par esta hecho a mano por artesanos con anos de experiencia.',
    tone_of_voice: 'Cercana, profesional y con personalidad western. Hablamos con la confianza de quien conoce su oficio y la pasion de quien ama lo que hace.',
  },
  assistant: {
    name: 'Eskin',
    personality: { warmth: 60, formality: 60, humor: 30, sales_aggressiveness: 60 },
    communication_style: 'warm' as const,
  },
  products: [
    {
      name: 'Grisly Negro Est. Nicole',
      price: 2900,
      description: 'Bota en color negro grabada en relieve con textura de pithon. Fabricada con piel original de res de la mas alta calidad. Diseno audaz y sofisticado que resalta el caracter y la personalidad de quien las usa.',
      benefits: 'Combinacion de tradicion y modernidad. Excelente para occasions casuales y formales. Resistente y duradera.',
      restrictions: 'Te sugerimos ordenar media talla menor. Ejemplo: si calzas talla 24, orderna 23.5.',
    },
    {
      name: 'Estambul Arena Est. Yalira',
      price: 2900,
      description: 'Bota en color arena con acabado texturizado. Piel de res de primera calidad con estampado exclusivo. Diseno elegante perfecto para el dia a dia.',
      benefits: 'Color versatil que combina con multiples outfits. Comoda para uso prolongado.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Grisly Negro Est. Steve',
      price: 2900,
      description: 'Variante del modelo Grisly con estampado Steve. Textura de pithon grabada en relieve sobre piel de res negro. Calidad artesanal premium.',
      benefits: 'Misma calidad y durabilidad del modelo Grisly. Diseno exclusivo.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Cabra Negro Kira',
      price: 3300,
      description: 'Bota de piel de cabra en color negro. Material mas suave y flexible que la res. Diseno elegante con acabado premium.',
      benefits: 'Piel de cabra mas suave y comoda. Se adapta al pie con el uso. Ligera y resistente.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Wash Off Forest Est. Auriane',
      price: 2900,
      description: 'Bota en color verde bosque con acabado wash off. Piel de res con estampado exclusivo. Diseno moderno y llamativo.',
      benefits: 'Color unico que destaca. Acabado wash off que le da un look informal y moderno.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Grisly Negro Est. Iliada',
      price: 2900,
      description: 'Version Iliada del modelo Grisly. Textura de pithon en negro con estampado exclusivo. Arte y calidad en cada detalle.',
      benefits: 'Diseno exclusivo Iliada. Misma calidad premium del modelo Grisly.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Wash Off Brandy Est. Syrelle',
      price: 2900,
      description: 'Bota en color brandy con acabado wash off. Piel de res de alta calidad con estampado Syrelle. Elegancia y estilo.',
      benefits: 'Color brandy ideal para combinations elegantes. Acabado wash off premium.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Cavalier Choco Est. Nicole',
      price: 2900,
      description: 'Bota en color chocolate con estampado Nicole. Piel de res de primera. Diseno clásico con toque moderno.',
      benefits: 'Color chocolate versatil. Estampado Nicole exclusivo. Comoda y resistente.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Lizard Negro Bronce Cincelado Flores',
      price: 2900,
      description: 'Bota de lizard en color negro bronce con cincelado a mano en forma de flores. Pieza artesanal unica.',
      benefits: 'Artesania pura, cada bota es unica. Cincelado hecho a mano por artesanos de Leon.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Alaska Orix Est. Amara',
      price: 2900,
      description: 'Bota Alaska en color orix con estampado Amara. Piel de res de alta calidad. Diseno western clasico.',
      benefits: 'Estilo Alaska retro. Piel durable y comoda. Perfecta para el look western.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Zale Black Cherry Est. Iralia',
      price: 2900,
      description: 'Bota en color black cherry (cereza negra) con estampado Iralia. Piel de res con tono unico y elegante.',
      benefits: 'Color cereza negra exclusivo. Estampado Iralia unico. Elegancia western.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Cavalier Cafe Est. Athala',
      price: 3000,
      description: 'Bota en color cafe con estampado Athala. Piel de res de primera calidad. Diseno versatil para multiples ocasiones.',
      benefits: 'Color cafe que combina con todo. Estampado exclusivo Athala.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Snake Black Est. Retro',
      price: 3000,
      description: 'Bota en color negro grabada en relieve con textura de python y fabricada con piel original de res de la mas alta calidad. Su diseno audaz y sofisticado resalta el caracter y la personalidad de quien las usa, combinando tradicion y modernidad.',
      benefits: 'Diseno snake exclusivo. Piel de res premium. Combinacion perfecta de tradicion y modernidad.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Cavalier Negro Est. Athala',
      price: 2900,
      description: 'Bota Cavalier en color negro con estampado Athala. Clasico diseno western en negro elegante.',
      benefits: 'Negro clasico que nunca pasa de moda. Diseno Cavalier comprobado.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Wash Off Negro Est. Marie',
      price: 2900,
      description: 'Bota en color negro con acabado wash off y estampado Marie. Piel de res de alta calidad.',
      benefits: 'Look informal y moderno con acabado wash off. Negro versatil.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Lizard Negro Bronce Est. Flores',
      price: 2900,
      description: 'Bota de lizard en negro bronce con cincelado de flores. Artesania pura de Leon, Guanajuato.',
      benefits: 'Pieza artesanal unica. Cincelado hecho a mano.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Cabra Cafe Kira',
      price: 3300,
      description: 'Bota de piel de cabra en color cafe. Material suave y flexible con acabado premium.',
      benefits: 'Piel de cabra mas suave que la res. Comoda y duradera.',
      restrictions: 'Ordenar media talla menor.',
    },
    {
      name: 'Grisly Rojo Est. Nicole',
      price: 2900,
      description: 'Variante en color rojo del modelo Grisly. Textura de pithon grabada en relieve. Atrevida y llamativa.',
      benefits: 'Color rojo que destaca. Misma calidad premium del modelo Grisly.',
      restrictions: 'Ordenar media talla menor.',
    },
  ],
  rules: [
    { category: 'zones', content: 'Enviamos a todo Mexico. El tiempo de entrega es de 3 a 5 dias habiles despues de confirmar el pedido. Envios a America del Sur disponibles con costo adicional.' },
    { category: 'zones', content: 'El envio es GRATIS en compras mayores a $2,500 MXN dentro de Mexico. Para pedidos menores, el costo de envio es de $150 MXN.' },
    { category: 'payment', content: 'Aceptamos PayPal, Mercado Pago y transferencia bancaria. Tambien aceptamos tarjetas de credito y debito a traves de nuestras pasarelas de pago.' },
    { category: 'payment', content: 'Ofrecemos hasta 6 MSI (meses sin intereses) en compras mayores a $2,000 MXN con tarjetas participantes.' },
    { category: 'restrictions', content: 'IMPORTANTE: Te sugerimos ordenar media talla MENOR de la que normalmente usas. Ejemplo: si normalmente usas talla 24, te recomendamos la 23.5. Esto se debe a que nuestras botas son de piel genuina y se amoldan al pie con el uso.' },
    { category: 'restrictions', content: 'Somos fabricantes artesanales de Leon, Guanajuato. Cada par esta hecho a mano, por lo que pueden haber variaciones minimas entre pares. Esto es parte de la artesania y no es un defecto.' },
    { category: 'schedule', content: 'Nuestro horario de atencion es de lunes a viernes de 9:00 a 18:00 horas y sabados de 9:00 a 14:00 horas. Los pedidos fuera de horario se procesan al siguiente dia habil.' },
    { category: 'promotions', content: 'Tenemos precios especiales para mayoreo y distribuidores. Si quieres vender nuestras botas en tu tienda o negocio, contactanos por WhatsApp al 477-188-9518 para precios mayoristas.' },
  ],
  instructions: [
    { instruction: 'Siempre menciona que somos fabricantes artesanales de Leon, Guanajuato. Esto es nuestra ventaja competitiva mas importante.', priority: 10 },
    { instruction: 'Cuando un cliente pregunte por tallas, SIEMPRE recomienda ordenar media talla menor. Explica que la piel genuina se amolda al pie con el uso.', priority: 10 },
    { instruction: 'Destaca la calidad de los materiales y el diseno artesanal en cada interaccion. No somos una marca mas, somos artesanos.', priority: 8 },
    { instruction: 'Si el cliente pregunta por mayoreo o distribucion, indica que contacte por WhatsApp al 477-188-9518 para precios especiales.', priority: 7 },
    { instruction: 'Nunca hagas descuentos sin autorizacion. Si el cliente pide descuento, menciona que tenemos MSI y envio gratis en compras mayores a $2,500.', priority: 9 },
  ],
}
