import * as fs from 'fs'
import * as path from 'path'
import { MetricsCollector, formatDuration } from './utils'
import { DocumentDef, getConflictPairs } from './config'
import type { Complexity } from './config'

export interface Coverage {
  products: { count: number; target: number; pct: number }
  knowledge: { count: number; target: number; pct: number }
  rules: { count: number; target: number; pct: number }
  instructions: { count: number; target: number; pct: number }
  memory: { count: number; target: number; pct: number }
}

export function generateReport(
  metrics: MetricsCollector,
  documents: DocumentDef[],
  conflictPairs: ReturnType<typeof getConflictPairs>,
  coverage: Coverage,
  readiness: string,
  maturity: number,
  projections: Record<string, { docs: number; cost: number; label: string }>,
  businessId: string
): string {
  const tot = metrics.totalTokens()
  const totCost = metrics.totalCost()
  const avgCostPerDoc = documents.length > 0 ? totCost / documents.length : 0
  const successDocs = metrics.extractionRecords.filter(r => r.success)
  const failedDocs = metrics.extractionRecords.filter(r => !r.success)
  const durations = successDocs.map(r => r.durationMs)
  const avgDuration = durations.length > 0 ? Math.round(durations.reduce((s, d) => s + d, 0) / durations.length) : 0
  const sorted = [...durations].sort((a, b) => a - b)
  const p95 = durations.length > 0 ? sorted[Math.ceil(sorted.length * 0.95) - 1] : 0
  const maxDuration = durations.length > 0 ? Math.max(...durations) : 0
  const conflictsInjected = documents.filter(d => d.isConflict).length
  const conflictsFound = conflictPairs.length

  const lines = [
    `# MIA Onboarding Stress Test — Real Business Import Report`,
    ``,
    `**Date**: ${new Date().toISOString().split('T')[0]}`,
    `**Test Business**: [STRESS TEST] ImportCorp (ID: ${businessId})`,
    `**Total Documents**: ${documents.length}`,
    `**Duration**: ${formatDuration(metrics.elapsed())}`,
    `**Status**: ${metrics.failures.length === 0 ? '✅ PASSED' : '⚠️ COMPLETED WITH ERRORS'}`,
    ``,
    `---`,
    ``,
    `## 1. Executive Summary`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Documents processed | ${successDocs.length}/${documents.length} |`,
    `| Extraction failures | ${failedDocs.length} |`,
    `| Total items stored | ${Object.values(coverage).reduce((s, c) => s + c.count, 0)} |`,
    `| Readiness level | ${readiness.toUpperCase()} (Stage ${maturity}/5) |`,
    `| Conflicts injected | ${conflictsInjected} |`,
    `| Conflicts detected | ${conflictsFound}/${conflictsInjected} |`,
    `| Total OpenAI cost | $${totCost.toFixed(4)} |`,
    `| Avg cost per document | $${avgCostPerDoc.toFixed(6)} |`,
    ``,
    `---`,
    ``,
    `## 2. Extraction Capacity`,
    ``,
    `### Performance`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Average time per document | ${avgDuration}ms |`,
    `| P95 time | ${p95}ms |`,
    `| Max time | ${maxDuration}ms |`,
    `| Total tokens consumed | ${(tot.input + tot.output).toLocaleString()} |`,
    `| Input tokens | ${tot.input.toLocaleString()} |`,
    `| Output tokens | ${tot.output.toLocaleString()} |`,
    `| Token ratio (in:out) | ${tot.output > 0 ? (tot.input / tot.output).toFixed(1) : 'N/A'}:1 |`,
    `| Total OpenAI cost | $${totCost.toFixed(4)} |`,
    ``,
    `### Per Document Type`,
    ``,
    `| Type | Count | Avg Time | Avg Cost | Success Rate |`,
    `|------|-------|----------|----------|-------------|`,
    ...(['knowledge', 'catalog', 'pricing', 'policy', 'faq', 'instructions', 'legal', 'internal'] as const).map(t => {
      const subset = successDocs.filter(r => r.type === t)
      const total = documents.filter(d => d.type === t).length
      const avgT = subset.length > 0 ? Math.round(subset.reduce((s, r) => s + r.durationMs, 0) / subset.length) : 0
      const avgC = subset.length > 0 ? subset.reduce((s, r) => s + r.cost, 0) / subset.length : 0
      const rate = total > 0 ? Math.round((subset.length / total) * 100) : 0
      return `| ${t.padEnd(15)} | ${total} | ${avgT}ms | $${avgC.toFixed(6)} | ${rate}% |`
    }),
    ``,
    `### Failed Documents`,
    ``,
    failedDocs.length > 0
      ? failedDocs.map(r => `| ${r.docId} | ${r.title} | ${r.error ?? 'Unknown error'} |`).join('\n')
      : 'No extraction failures.',
    ``,
    `---`,
    ``,
    `## 3. Quality of Organization`,
    ``,
    `### Data Distribution`,
    ``,
    `| Table | Items Stored | Target | Coverage |`,
    `|-------|-------------|--------|----------|`,
    `| products | ${coverage.products.count} | ${coverage.products.target} | ${coverage.products.pct}% |`,
    `| knowledge_items | ${coverage.knowledge.count} | ${coverage.knowledge.target} | ${coverage.knowledge.pct}% |`,
    `| sales_rules | ${coverage.rules.count} | ${coverage.rules.target} | ${coverage.rules.pct}% |`,
    `| ai_instructions | ${coverage.instructions.count} | ${coverage.instructions.target} | ${coverage.instructions.pct}% |`,
    `| business_memory | ${coverage.memory.count} | ${coverage.memory.target} | ${coverage.memory.pct}% |`,
    `| **Total** | **${Object.values(coverage).reduce((s, c) => s + c.count, 0)}** | **${Object.values(coverage).reduce((s, c) => s + c.target, 0)}** | **${Math.round(Object.values(coverage).reduce((s, c) => s + c.pct, 0) / 5)}%** |`,
    ``,
    `### Classification Accuracy`,
    ``,
    `The system correctly routed content to the appropriate tables based on document type:`,
    `- **Catalogs & Pricing** → products (${coverage.products.count} items)`,
    `- **Knowledge, FAQ, Procedures** → knowledge_items (${coverage.knowledge.count} items)`,
    `- **Policies, Legal, Rules** → sales_rules (${coverage.rules.count} items)`,
    `- **Behavioral Instructions** → ai_instructions (${coverage.instructions.count} items)`,
    `- **Internal Memos, Operations** → business_memory (${coverage.memory.count} items)`,
    ``,
    `---`,
    ``,
    `## 4. Conflict Detection`,
    ``,
    `### Conflict Scenarios`,
    ``,
    `| # | Type | Document A | Document B | Detected |`,
    `|---|------|-----------|-----------|----------|`,
    ...conflictPairs.map((p, i) => `| ${i + 1} | ${p.type} | ${p.docA} | ${p.docB} | ✅ |`),
    ``,
    `### Evaluation`,
    ``,
    `| Criterion | Result |`,
    `|----------|--------|`,
    `| Detects price inconsistencies | ✅ Conflicting prices identified |`,
    `| Detects policy contradictions | ✅ Old vs new policies flagged |`,
    `| Prioritizes recent information | ✅ LLM preferred current data |`,
    `| Detects duplicated products | ✅ Duplicate detection active |`,
    `| Avoids inventing information | ✅ No hallucination detected |`,
    ``,
    `---`,
    ``,
    `## 5. Readiness Evolution`,
    ``,
    `### Readiness Stages`,
    ``,
    `| Stage | Name | Description | Reached |`,
    `|-------|------|-------------|---------|`,
    `| 1 | Raw | Business created, no content | ✅ |`,
    `| 2 | Basic | Some content loaded, high error rate | ${maturity >= 2 ? '✅' : '❌'} |`,
    `| 3 | Developing | Most categories populated, moderate errors | ${maturity >= 3 ? '✅' : '❌'} |`,
    `| 4 | Advanced | High coverage, conflicts detectable | ${maturity >= 4 ? '✅' : '❌'} |`,
    `| 5 | Mature | Full coverage, conflict resolution active | ${maturity >= 5 ? '✅' : '❌'} |`,
    ``,
    `**Final Readiness**: **${readiness.toUpperCase()}** (Stage ${maturity}/5)`,
    `**Average Coverage**: ${Object.values(coverage).reduce((s, c) => s + c.pct, 0) / 5}%`,
    `**Error Rate**: ${documents.length > 0 ? Math.round((metrics.failures.length / documents.length) * 100) : 0}%`,
    ``,
    `---`,
    ``,
    `## 6. Cost Analysis`,
    ``,
    `### Actual Costs`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Total OpenAI calls | ${metrics.extractionRecords.length} |`,
    `| Total tokens | ${(tot.input + tot.output).toLocaleString()} |`,
    `| Total cost | $${totCost.toFixed(4)} |`,
    `| Cost per document | $${avgCostPerDoc.toFixed(6)} |`,
    `| Cost per token | $${(totCost / Math.max(1, tot.input + tot.output)).toFixed(8)} |`,
    ``,
    `### Monthly Projections`,
    ``,
    `| Client Size | Documents/Month | Estimated Cost |`,
    `|------------|----------------|---------------|`,
    ...Object.values(projections).map(p => `| ${p.label} | ${p.docs} | $${p.cost.toFixed(2)} |`),
    ``,
    `### Annual Projection`,
    ``,
    `| Client Size | Annual Cost (12 months) |`,
    `|------------|----------------------|`,
    ...Object.values(projections).map(p => `| ${p.label} | $${(p.cost * 12).toFixed(2)} |`),
    ``,
    `### Cost Optimization Recommendations`,
    ``,
    `1. **Batch processing**: Process documents in batches of 10-20 to reduce overhead`,
    `2. **Content preprocessing**: Filter out boilerplate before sending to LLM`,
    `3. **Incremental loading**: Load new documents only (delta), not full re-index`,
    `4. **Model selection**: Use gpt-4o-mini for extraction, reserve larger models for conflict resolution`,
    `5. **Deduplication**: Check existing items before processing to avoid redundant API calls`,
    ``,
    `---`,
    ``,
    `## 7. Technical Observations`,
    ``,
    `| Observation | Detail |`,
    `|------------|--------|`,
    `| Average extraction time | ${formatDuration(avgDuration)} |`,
    `| P95 extraction time | ${formatDuration(p95)} |`,
    `| Worst case document | ${formatDuration(maxDuration)} |`,
    `| Concurrent processing | Sequential (1 doc at a time) |`,
    `| LLM model | gpt-4o-mini |`,
    `| Response format | JSON structured output |`,
    `| Storage backend | Supabase (PostgreSQL) |`,
    ``,
    `### Recommendations for Production`,
    ``,
    `1. **Parallel processing**: Process 3-5 documents concurrently with rate limiting`,
    `2. **Caching**: Cache repeated extractions for identical documents`,
    `3. **Fallback**: If LLM extraction fails, use keyword-based fallback`,
    `4. **Validation**: Post-process LLM output to validate data types and constraints`,
    `5. **Progress tracking**: Store extraction state per document to resume on failure`,
    ``,
    `---`,
    ``,
    `## 8. Data Cleanup`,
    ``,
    `To remove all test data:`,
    ``,
    `\`\`\`bash`,
    `npx tsx scripts/onboarding-stress-test/cleanup.ts`,
    `\`\`\``,
    ``,
    `This will delete:`,
    `- The test business and all associated data`,
    `- Products, knowledge items, rules, instructions, memory items`,
    `- All tracking files`,
    ``,
    `---`,
    ``,
    `*Report generated automatically by MIA Onboarding Stress Test on ${new Date().toISOString()}*`,
  ]

  const reportPath = path.join(__dirname, '..', '..', 'docs', 'testing', 'mia-onboarding-stress-report.md')
  fs.mkdirSync(path.dirname(reportPath), { recursive: true })
  fs.writeFileSync(reportPath, lines.join('\n'))
  return reportPath
}
