import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

/**
 * Structural checks on the generated database types.
 *
 * `src/lib/supabase/schema.typecheck.ts` is the compile-time alarm: it fails
 * when the type stops rejecting bad columns. These are the runtime counterpart,
 * so `npm run test:unit` alone also catches a generator that produced a file
 * which parses but says the wrong thing.
 *
 * Both of the real defects found while building this started as a file that
 * compiled while claiming the wrong thing: one missing comma between generated
 * relationships, and a column declared as Json because a type name was passed
 * through in the wrong case.
 */

const GENERATED_PATH = resolve(process.cwd(), 'src/lib/supabase/database.generated.ts')
const source = readFileSync(GENERATED_PATH, 'utf8')

describe('generated database types', () => {
  it('declares every schema the app queries', () => {
    expect(source).toContain('  public: {')
    expect(source).toContain('  delivery: {')
    expect(source).toContain('  inventory: {')
  })

  it('renders every table with all three row shapes', () => {
    // `Row: {` followed by a blank line means a table parsed with no columns,
    // which silently types the table as empty instead of failing.
    expect(source).not.toMatch(/Row: \{\s*\n\s*\}/)
    expect(source).not.toMatch(/Insert: \{\s*\n\s*\}/)
    expect(source).not.toMatch(/Update: \{\s*\n\s*\}/)
  })

  it('does not fall back to any', () => {
    expect(source).not.toMatch(/:\s*any\b/)
  })

  it('types the two column layouts this codebase got wrong', () => {
    // knowledge_items holds question/answer, not content.
    const knowledge = source.slice(source.indexOf('knowledge_items: {'))
    const block = knowledge.slice(0, knowledge.indexOf('Relationships:'))
    expect(block).toContain('question: string')
    expect(block).toContain('answer: string')

    // conversations reaches its tenant through assistant_id, not business_id.
    const conversations = source.slice(source.indexOf('conversations: {'))
    const conversationBlock = conversations.slice(0, conversations.indexOf('Relationships:'))
    expect(conversationBlock).not.toContain('business_id')
    expect(conversationBlock).toContain('assistant_id: string')
  })

  it('emits foreign keys so embedded selects are typed instead of never', () => {
    const relationships = source.match(/Relationships: \[\n/g) ?? []
    expect(relationships.length).toBeGreaterThan(0)
  })

  it('is not hand-edited away from the generator', () => {
    expect(source).toContain('AUTO-GENERATED by scripts/generate-db-types.ts')
  })
})
